name: CI/CD Web Dinamis (Next.js)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web-dinamis/**'
      - '.github/workflows/deploy-dinamis.yml'

jobs:
  build-dinamis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Web Dinamis
        uses: docker/build-push-action@v5
        with:
          context: ./web-dinamis
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-dinamis:latest

  deploy-ke-aws:
    needs: build-dinamis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Remove dummy SQL directory on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            rm -rf /home/ubuntu/production-monorepo/database/admserver.sql

      - name: Copy Compose file to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "web-dinamis/docker-compose.yml,web-dinamis/database/admserver.sql"
          target: "/home/ubuntu/production-monorepo"
          strip_components: 1

      - name: SSH to EC2 and Run Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/production-monorepo
            docker compose pull
            docker compose up -d
  
            docker compose restart
